service: notification

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonSNSFullAccess
custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules

functions:
  history-fetch:
    handler: src/functions/history-fetch/handler.historyFetch
    events:
      - http:
          method: get
          path: history
          cors: true

# plugins can be added here
plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-prune-plugin



